# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tmKXwPhYAzmZiH8c0Ow7AzSLBjYD8ooI
"""

x=input("Enter The Values That is Needed to be Sorted :")
li=[int (i) for i in x.split()]

print(li)

print(type(li))

li.reverse()
print(li)

li.sort()
li.reverse()
print(li)

